export { B2BDashboardScreen } from './screens/B2BDashboardScreen';
export { StudentsScreen } from './screens/StudentsScreen';
export { StudentDetailScreen } from './screens/StudentDetailScreen';
export { AlertsScreen } from './screens/AlertsScreen';
export { StatsScreen } from './screens/StatsScreen';
export { SchoolTasksScreen } from './screens/SchoolTasksScreen';
export { SettingsScreen } from './screens/SettingsScreen';
export { BrandingScreen } from './screens/BrandingScreen';
export { useB2BDashboard } from './hooks/useB2BDashboard';
export { useStudents } from './hooks/useStudents';
export type { Institution, StudentSummary, Alert } from './types/admin.types';
